### ISSUE TITLE
How to get clarity sass variables into Angular library?

### ISSUE THREAD

**Issue by whizkidwwe1217** [porscheinformatik/clarity-addons#215]
How were you able to reference clarity-ui theme variables from node_modules into the Angular library?
![image](https://user-images.githubusercontent.com/1977391/45726374-9e2c0e80-bbf1-11e8-9721-0735a9a393ea.png)
I tried what clr-addons did but I got the following errors:
![image](https://user-images.githubusercontent.com/1977391/45726442-e0ede680-bbf1-11e8-9504-6af406be988e.png)

**Comment by whizkidwwe1217** [comment]
Okay, I got it. I actually made the scss compilation working after I followed your approach. The default clarity themes & vu3 worked perfectly. But I'm having one issue.

I have a custom control with custom scss, I'm expecting that the `$clr-global-selection-color` is a default color variable of clarity. So I use it in my custom control as show below:

```css
.toolbar {
   &:hover {
       background: $clr-global-selection-color;
   }
}
```

I compiled the scss theme files.
First, it compiles the clarity default light theme correctly with the correct color of the `$clr-global-selection-color`.
Then, it compiles the clarity dark theme. However, the `$clr-global-selection-color` doesn't get the dark color and when I checked the css, it's still using the same color as the light theme. Am I missing something?

[hordeflowkit.zip](https://github.com/porscheinformatik/clarity-addons/files/2396330/hordeflowkit.zip)

**Comment by whizkidwwe1217** [comment]
@Wallabeng Hmmm.. If I remove that, I'm getting "No mixin named exports" error.
![image](https://user-images.githubusercontent.com/1977391/45744640-a1df8580-bc31-11e8-9287-72ad43953193.png)

**Comment by Wallabeng** [comment]
What I also saw is that you import components.clarity twice in dark theme, because you import the whole theme in the first line.
clr-ui-dark.scss should look like that:
@import "./utils/dependencies.clarity";
@import "./utils/theme.dark.clarity";
@import '../../components.variables.hordeflow';
@import "./utils/components.clarity";
@import '../../components.hordeflowkit';

And from your logs i guess you are including your scss in your component with "styleUrls"?
This will not work anymore, you have to precompile the css files.

**Comment by whizkidwwe1217** [comment]
@Wallabeng Like you've said, I reorganized the imports and remove it scss in styleUrls. I finally made it working!!!Thank you very much for your help. You're a life-saver.
